### PR TITLE
add app icon, fix #33

### LINKED ISSUE #33: Icon
This app needs an icon :)

cc @jancborchardt

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @MorrisJobke, fix #33

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@jancborchardt what icon is this? white icons on transparent background = great fun to view ;-)

**Comment by MorrisJobke** [comment]
Gear icon:

bildschirmfoto von 2015-05-12 14-42-58

**Comment by MorrisJobke** [comment]
:+1:

**Comment by jancborchardt** [comment]
@DeepDiver1975 pr0tip: Click and drag the icon over something dark on your screen, then you’ll be able to see it. ;) Or github should go and fix their damn SVG display algorithm :D

**Comment by karlitschek** [comment]
:+1:

**Pull request merged**
